name: Deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.VPS_HOST }}
        ssh_private_key: ${{ secrets.VPS_PRIVATE_KEY }}
        ssh_user: ${{ secrets.VPS_USER }}
        docker_compose_prefix: TBSchema
